version: '3.8'
services:
  # a container for each service, app, etc
  api:
    image: 25805503/fastapi_blog_project:1.1
    depends_on:
      - postgres
    ports:
      - 8000:8000
    env_file:
      - ./.env
    # command: alembic upgrade head gunicorn -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 app.main:app
  postgres:
    image: postgres
    # environment:
    #   - DATABASE_HOSTNAME=${DATABASE_HOSTNAME} # to use environment variables on host machine
    env_file:
      - ./.env
    ports:
      - 5433:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  # will create necessary volumes on host at /var/lib/docker/volumes; an empty volume means that docker manages the volume and persistant data
  postgres-db:
